name: aspen_travel_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  get: ^4.6.5
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.5
  dropdown_button2: ^2.3.9
  card_swiper: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/back/intro_back.jpg
    - assets/back/land.jpg
    - assets/icons/aspen.svg
    - assets/icons/Heart.svg
    - assets/icons/Home.svg
    - assets/icons/Profile.svg
    - assets/icons/Ticket.svg
    - assets/icons/Location.svg
    - assets/icons/Search.svg
